#pragma once

#include <stdint.h>

// Generated by scripts/train_vision_feature_model.py.
// Tiny softmax feature classifier for the first offline CoreS3 vision model.
// Synthetic validation accuracy: 0.908
static constexpr uint16_t kVisionInputWidth = 64;
static constexpr uint16_t kVisionInputHeight = 64;
static constexpr uint8_t kVisionInputChannels = 3;
static constexpr uint32_t kVisionInputBytes =
    static_cast<uint32_t>(kVisionInputWidth) * kVisionInputHeight * kVisionInputChannels;
static constexpr uint8_t kVisionFeatureCount = 10;
static constexpr uint8_t kVisionClassCount = 8;
static constexpr int16_t kVisionFeatureScale = 64;

static const char* const kVisionClassLabels[kVisionClassCount] = {
    "plant_leaf",
    "food_fruit",
    "paper_book",
    "electronics_screen",
    "metal_key_coin",
    "fabric_cloth",
    "cup_bottle_water",
    "toy_figure",
};

static const int16_t kVisionWeights[kVisionClassCount][kVisionFeatureCount] = {
    {-255, 243, -210, -22, 67, 20, 4, -70, -46, 99},
    {247, 42, -329, 14, 182, 29, 7, 1, -5, 37},
    {208, 139, 49, 127, -116, -168, -16, -21, -10, -68},
    {-250, -236, -130, -181, -103, 111, 34, 183, -9, -40},
    {144, 236, 239, 94, -185, 126, -5, -25, 129, -55},
    {-21, -133, -97, -60, -57, -203, -84, -28, -116, -31},
    {-267, -22, 330, 70, 40, -30, -4, -12, 65, -5},
    {193, -269, 149, -41, 171, 115, 65, -28, -9, 62},
};

static const int32_t kVisionBias[kVisionClassCount] = {
    3783, 1817, -11807, 6925, -2901, -12486, 5603, 9066
};

static const uint8_t kVisionModelData[] = {
    0x58, 0x48, 0x53, 0x50, 0x45, 0x54, 0x46, 0x31
};
static constexpr uint32_t kVisionModelDataLen = sizeof(kVisionModelData);
