#pragma once

#include <stdint.h>

// Generated by scripts/train_vision_feature_model.py.
// Lightweight prototype-distance classifier for CoreS3 offline vision.
// Data quality: weak
// Positive validation accuracy: 0.089
// Negative false positive rate: 0.150
static constexpr uint16_t kVisionInputWidth = 64;
static constexpr uint16_t kVisionInputHeight = 64;
static constexpr uint8_t kVisionInputChannels = 3;
static constexpr uint32_t kVisionInputBytes =
    static_cast<uint32_t>(kVisionInputWidth) * kVisionInputHeight * kVisionInputChannels;
static constexpr uint8_t kVisionFeatureCount = 18;
static constexpr uint8_t kVisionClassCount = 8;
static constexpr uint8_t kVisionDistanceScale = 16;
static constexpr uint16_t kVisionMinDistanceMargin = 3;
static constexpr bool kVisionModelQualityWeak = true;

static const char* const kVisionClassLabels[kVisionClassCount] = {
    "plant_leaf",
    "food_fruit",
    "paper_book",
    "electronics_screen",
    "metal_key_coin",
    "fabric_cloth",
    "cup_bottle_water",
    "toy_figure",
};

static const char* const kVisionFeatureNames[kVisionFeatureCount] = {
    "red",
    "green",
    "blue",
    "brightness",
    "saturation",
    "contrast",
    "center_brightness",
    "edge_brightness",
    "center_saturation",
    "edge_saturation",
    "center_delta",
    "dark_ratio",
    "bright_ratio",
    "red_dominance",
    "green_dominance",
    "blue_dominance",
    "warm_score",
    "low_saturation_score",
};

static const uint8_t kVisionFeatureWeights[kVisionFeatureCount] = {
    5, 5, 5, 4, 6, 5, 4, 3, 4, 3, 7, 5, 4, 6, 6, 6, 5, 5
};

static const uint8_t kVisionPrototype[kVisionClassCount][kVisionFeatureCount] = {
    {120, 117, 91, 109, 51, 100, 113, 108, 57, 49, 41, 38, 16, 129, 124, 91, 156, 125},
    {138, 114, 79, 111, 70, 98, 107, 112, 85, 64, 50, 34, 15, 151, 104, 68, 174, 86},
    {123, 110, 97, 110, 36, 98, 115, 108, 36, 36, 31, 42, 12, 140, 114, 101, 147, 160},
    {116, 113, 110, 113, 31, 121, 118, 111, 34, 31, 49, 52, 30, 126, 117, 118, 132, 173},
    {132, 117, 99, 116, 38, 102, 118, 115, 45, 36, 47, 32, 23, 143, 112, 94, 154, 156},
    {122, 111, 101, 111, 37, 107, 108, 112, 40, 36, 36, 49, 21, 137, 114, 105, 143, 158},
    {130, 111, 94, 112, 48, 105, 111, 112, 55, 45, 44, 44, 21, 145, 107, 91, 154, 132},
    {131, 114, 99, 114, 48, 108, 115, 114, 54, 46, 43, 39, 23, 144, 110, 94, 152, 133},
};

static const uint8_t kVisionStd[kVisionClassCount][kVisionFeatureCount] = {
    {34, 31, 38, 30, 30, 29, 34, 33, 39, 29, 31, 40, 30, 25, 26, 30, 28, 67},
    {40, 34, 38, 32, 35, 26, 32, 35, 46, 34, 35, 38, 26, 31, 31, 34, 29, 63},
    {37, 34, 35, 33, 22, 28, 39, 35, 24, 22, 26, 42, 27, 18, 16, 25, 20, 54},
    {38, 37, 41, 36, 24, 37, 47, 39, 30, 24, 36, 45, 39, 24, 14, 25, 24, 58},
    {38, 37, 41, 36, 31, 30, 36, 41, 39, 30, 35, 39, 40, 19, 18, 33, 27, 75},
    {43, 41, 41, 40, 22, 32, 43, 41, 29, 22, 27, 52, 35, 19, 15, 25, 21, 57},
    {38, 39, 42, 36, 29, 28, 42, 38, 39, 28, 32, 44, 36, 26, 22, 32, 26, 68},
    {38, 37, 39, 35, 31, 28, 34, 39, 35, 31, 27, 39, 37, 21, 19, 32, 26, 70},
};

static const uint16_t kVisionClassThresholds[kVisionClassCount] = {
    240, 240, 240, 240, 240, 240, 240, 240
};

static const uint8_t kVisionNegativePrototype[kVisionFeatureCount] = {
    141, 136, 125, 134, 23, 42, 135, 134, 23, 23, 12, 31, 42, 133, 121, 110, 141, 195
};

static const uint8_t kVisionNegativeStd[kVisionFeatureCount] = {
    61, 61, 60, 60, 23, 47, 60, 60, 25, 23, 18, 69, 87, 16, 12, 22, 18, 61
};

static constexpr uint16_t kVisionNegativeThreshold = 220;

static const uint8_t kVisionModelData[] = {
    0x4d, 0x35, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x31
};
static constexpr uint32_t kVisionModelDataLen = sizeof(kVisionModelData);
