from __future__ import annotations

import math
import random
from pathlib import Path


CLASSES = [
    "plant_leaf",
    "food_fruit",
    "paper_book",
    "electronics_screen",
    "metal_key_coin",
    "fabric_cloth",
    "cup_bottle_water",
    "toy_figure",
]

FEATURES = [
    "red",
    "green",
    "blue",
    "brightness",
    "saturation",
    "contrast",
    "center_delta",
    "dark_ratio",
    "bright_ratio",
    "center_sat_minus_edge_sat",
]


PROTOTYPES = {
    "plant_leaf": (78, 175, 74, 130, 100, 70, 42, 4, 5, 30),
    "food_fruit": (205, 126, 48, 135, 150, 84, 45, 5, 8, 24),
    "paper_book": (190, 178, 150, 176, 35, 52, 36, 1, 18, 6),
    "electronics_screen": (46, 58, 82, 58, 55, 118, 48, 45, 4, 12),
    "metal_key_coin": (188, 190, 180, 178, 22, 98, 35, 2, 25, 0),
    "fabric_cloth": (135, 115, 105, 116, 72, 38, 34, 6, 5, 18),
    "cup_bottle_water": (80, 128, 196, 150, 95, 72, 44, 3, 20, 18),
    "toy_figure": (190, 64, 150, 126, 145, 115, 55, 7, 10, 28),
}


NOISE = (30, 30, 30, 34, 36, 34, 24, 12, 12, 18)
SCALE = 64
LR = 0.055
L2 = 0.0007
EPOCHS = 700


def clamp(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def normalize(sample: tuple[float, ...]) -> list[float]:
    return [clamp((v / 127.5) - 1.0, -1.0, 1.0) for v in sample]


def make_dataset() -> list[tuple[list[float], int]]:
    rng = random.Random(0x57355054)
    rows: list[tuple[list[float], int]] = []
    for class_id, name in enumerate(CLASSES):
        proto = PROTOTYPES[name]
        for _ in range(180):
            sample = []
            for value, noise in zip(proto, NOISE):
                sample.append(clamp(value + rng.gauss(0.0, noise), 0, 255))
            rows.append((normalize(tuple(sample)), class_id))
    rng.shuffle(rows)
    return rows


def softmax(logits: list[float]) -> list[float]:
    peak = max(logits)
    exps = [math.exp(v - peak) for v in logits]
    total = sum(exps)
    return [v / total for v in exps]


def train() -> tuple[list[list[float]], list[float], float]:
    data = make_dataset()
    class_count = len(CLASSES)
    feature_count = len(FEATURES)
    weights = [[0.0 for _ in range(feature_count)] for _ in range(class_count)]
    bias = [0.0 for _ in range(class_count)]

    for epoch in range(EPOCHS):
        random.Random(epoch).shuffle(data)
        for features, label in data:
            logits = [
                bias[c] + sum(weights[c][i] * features[i] for i in range(feature_count))
                for c in range(class_count)
            ]
            probs = softmax(logits)
            for c in range(class_count):
                target = 1.0 if c == label else 0.0
                grad = probs[c] - target
                bias[c] -= LR * grad
                for i, feature in enumerate(features):
                    weights[c][i] -= LR * (grad * feature + L2 * weights[c][i])

    correct = 0
    for features, label in data:
        logits = [
            bias[c] + sum(weights[c][i] * features[i] for i in range(feature_count))
            for c in range(class_count)
        ]
        if max(range(class_count), key=lambda c: logits[c]) == label:
            correct += 1
    return weights, bias, correct / len(data)


def emit_header(weights: list[list[float]], bias: list[float], acc: float) -> str:
    quant_w = [[round(v * SCALE) for v in row] for row in weights]
    quant_b = [round(v * SCALE * SCALE) for v in bias]
    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "// Generated by scripts/train_vision_feature_model.py.",
        "// Tiny softmax feature classifier for the first offline CoreS3 vision model.",
        f"// Synthetic validation accuracy: {acc:.3f}",
        "static constexpr uint16_t kVisionInputWidth = 64;",
        "static constexpr uint16_t kVisionInputHeight = 64;",
        "static constexpr uint8_t kVisionInputChannels = 3;",
        "static constexpr uint32_t kVisionInputBytes =",
        "    static_cast<uint32_t>(kVisionInputWidth) * kVisionInputHeight * kVisionInputChannels;",
        "static constexpr uint8_t kVisionFeatureCount = 10;",
        "static constexpr uint8_t kVisionClassCount = 8;",
        f"static constexpr int16_t kVisionFeatureScale = {SCALE};",
        "",
        "static const char* const kVisionClassLabels[kVisionClassCount] = {",
    ]
    lines += [f'    "{name}",' for name in CLASSES]
    lines += [
        "};",
        "",
        "static const int16_t kVisionWeights[kVisionClassCount][kVisionFeatureCount] = {",
    ]
    for row in quant_w:
        lines.append("    {" + ", ".join(str(v) for v in row) + "},")
    lines += [
        "};",
        "",
        "static const int32_t kVisionBias[kVisionClassCount] = {",
        "    " + ", ".join(str(v) for v in quant_b),
        "};",
        "",
        "static const uint8_t kVisionModelData[] = {",
        "    0x58, 0x48, 0x53, 0x50, 0x45, 0x54, 0x46, 0x31",
        "};",
        "static constexpr uint32_t kVisionModelDataLen = sizeof(kVisionModelData);",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    weights, bias, acc = train()
    out = Path("arduino_demos/04_camera_pet_battle/vision_model_data.h")
    out.write_text(emit_header(weights, bias, acc), encoding="utf-8")
    print(f"wrote {out} accuracy={acc:.3f}")


if __name__ == "__main__":
    main()

